/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.21
 * Generated at: 2015-04-17 22:24:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ceo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE HTML>\n");
      out.write("<!--\n");
      out.write("\n");
      out.write("AUTHOR                      : LNMIIT_ONLINE_VOTING_SYSTEM_DEVELOPMENT_TEAM_GROUP-26 SEPM2015\n");
      out.write("DATE OF LAST UPDATE         : 17 APRIL 2015 \n");
      out.write("\n");
      out.write("-->\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<title>CEO_TERMINAL: LNMIIT ONLINE VOTING SYSTEM</title>\n");
      out.write("\t\t<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("\t\t<meta name=\"description\" content=\"\" />\n");
      out.write("\t\t<meta name=\"keywords\" content=\"\" />\n");
      out.write("\t\t<!--[if lte IE 8]><script src=\"css/ie/html5shiv.js\"></script><![endif]-->\n");
      out.write("\t\t<script src=\"js/jquery.min.js\"></script>\n");
      out.write("\t\t<script src=\"js/jquery.dropotron.min.js\"></script>\n");
      out.write("\t\t<script src=\"js/jquery.scrolly.min.js\"></script>\n");
      out.write("\t\t<script src=\"js/jquery.scrollgress.min.js\"></script>\n");
      out.write("\t\t<script src=\"js/skel.min.js\"></script>\n");
      out.write("\t\t<script src=\"js/skel-layers.min.js\"></script>\n");
      out.write("\t\t<script src=\"js/init.js\"></script>\n");
      out.write("\t\t<noscript>\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"css/skel.css\" />\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"css/style.css\" />\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"css/style-wide.css\" />\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"css/style-noscript.css\" />\n");
      out.write("\t\t</noscript>\n");
      out.write("\t\t<!--[if lte IE 8]><link rel=\"stylesheet\" href=\"css/ie/v8.css\" /><![endif]-->\n");
      out.write("\t\t<!--[if lte IE 9]><link rel=\"stylesheet\" href=\"css/ie/v9.css\" /><![endif]-->\n");
      out.write("\t</head>\n");
      out.write("\t<body class=\"index\">\n");
      out.write("\n");
      out.write("\t\t<!-- Header -->\n");
      out.write("\t\t\t<header id=\"header\" class=\"alt\">\n");
      out.write("\t\t\t<h1 id=\"logo\"><a href=\"http://www.lnmiit.ac.in\"><img src=\"images/LNMIIT_logo.png\" width=\"200px\" height=\"100px\"></a></h1>\t\t<nav id=\"nav\">\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"index.jsp\">Welcome</a></li>\n");
      out.write("\t\t\t\t\t\t<!--<li class=\"submenu\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"\">Layouts</a>\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"left-sidebar.html\">Left Sidebar</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"right-sidebar.html\">Right Sidebar</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"no-sidebar.html\">No Sidebar</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"contact.html\">Contact</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"submenu\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"\">Submenu</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Dolore Sed</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Consequat</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Lorem Magna</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Sed Magna</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Ipsum Nisl</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"button special\">Sign Up</a></li>-->\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\">Election Rules</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\">Help Page</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\">Contact Us</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"logout.jsp\" class=\"button special\">LOGOUT</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</nav>\n");
      out.write("\t\t\t</header>\n");
      out.write("\n");
      out.write("\t\t<!-- Banner -->\n");
      out.write("\t\t\t<section id=\"banner\">\n");
      out.write("\n");
      out.write("\t\t\t\t<!--\n");
      out.write("\t\t\t\t\t\".inner\" is set up as an inline-block so it automatically expands\n");
      out.write("\t\t\t\t\tin both directions to fit whatever's inside it. This means it won't\n");
      out.write("\t\t\t\t\tautomatically wrap lines, so be sure to use line breaks where\n");
      out.write("\t\t\t\t\tappropriate (<br />).\n");
      out.write("\t\t\t\t-->\n");
      out.write("\t\t\t\t<div class=\"inner\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<header>\n");
      out.write("\t\t\t\t\t\t<h3>Welcome to the Chief Election Officer</h3>\n");
      out.write("\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t<br/><br/>\n");
      out.write("\t\t\t\t\t<p class=\"ceo_quote\">\"Elections belong to the people. It's their decision. <br/>If they decide to turn their back on the fire <br/>and burn their behinds,then they will just<br/> have to sit on their blisters.\"<br/><br/></p>\n");
      out.write("\t\t\t\t\t<p class=\"ceo_quote\">-Abraham Lincoln</p>\t\t\n");
      out.write("\t           \n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</section>\n");
      out.write("\t\t<!--End of banner-->\n");
      out.write("\n");
      out.write("\t\t<!-- Main -->\n");
      out.write("\t\t\t<article id=\"main\">\n");
      out.write("\n");
      out.write("\t\t\t\t<header class=\"special container\">\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t</header>\n");
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<!-- CEO's Operations -->\n");
      out.write("\t\t\t\t\t<section class=\"wrapper style3 container special\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<header class=\"major\">\n");
      out.write("\t\t\t\t\t\t\t<h2>Time to <strong>Act</strong></h2>\n");
      out.write("\t\t\t\t\t\t</header>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"6u 12u(narrower)\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<section>\n");
      out.write("\t\t\t\t\t\t\t\t\t<header>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3><a href=\"#\">CREATE ELECTION EVENT</a></h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p></p>\n");
      out.write("\t\t\t\t\t\t\t\t</section>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"6u 12u(narrower)\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<section>\n");
      out.write("\t\t\t\t\t\t\t\t\t<header>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3><a href=\"#\">UPDATE ELECTION EVENT</a></h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p></p>\n");
      out.write("\t\t\t\t\t\t\t\t</section>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"6u 12u(narrower)\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<section>\n");
      out.write("\t\t\t\t\t\t\t\t\t<header>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3><a href=\"#\">DELETE ELECTION EVENT</a></h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p></p>\n");
      out.write("\t\t\t\t\t\t\t\t</section>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"6u 12u(narrower)\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<section>\n");
      out.write("\t\t\t\t\t\t\t\t\t<header>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3><a href=\"#\">ABORT ELECTION RESULTS</a></h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p></p>\n");
      out.write("\t\t\t\t\t\t\t\t</section>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"6u 12u(narrower)\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<section>\n");
      out.write("\t\t\t\t\t\t\t\t\t<header>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3><a href=\"#\">VIEW CANDIDATURE APPLICATION</a></h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p></p>\n");
      out.write("\t\t\t\t\t\t\t\t</section>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"6u 12u(narrower)\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<section>\n");
      out.write("\t\t\t\t\t\t\t\t\t<header>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<h3><a href=\"#\">VIEW CANDIDATE PORTFOLIO</a></h3>\n");
      out.write("\t\t\t\t\t\t\t\t\t</header>\n");
      out.write("\t\t\t\t\t\t\t\t\t<p></p>\n");
      out.write("\t\t\t\t\t\t\t\t</section>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<footer class=\"major\">\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"buttons\">\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"button\">PUBLISH RESULTS</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t</footer>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</section> <!--END OF CEO OPERATIONS -->\n");
      out.write("\n");
      out.write("\t\t\t</article>\n");
      out.write("\n");
      out.write("\t\t<!-- CTA -->\n");
      out.write("\t\t\t<section id=\"cta\">\n");
      out.write("\n");
      out.write("\t\t\t\t<header>\n");
      out.write("\t\t\t\t\t<h2>Ready to do <strong>something</strong>?</h2>\n");
      out.write("\t\t\t\t\t<p>Proin a ullamcorper elit, et sagittis turpis integer ut fermentum.</p>\n");
      out.write("\t\t\t\t</header>\n");
      out.write("\t\t\t\t<footer>\n");
      out.write("\t\t\t\t\t<ul class=\"buttons\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"button special\">Take My Money</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"button\">LOL Wut</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</footer>\n");
      out.write("\n");
      out.write("\t\t\t</section>\n");
      out.write("\n");
      out.write("\t\t<!-- Footer -->\n");
      out.write("\t\t\t<footer id=\"footer\">\n");
      out.write("\n");
      out.write("\t\t\t\t<ul class=\"icons\">\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" class=\"icon circle fa-twitter\"><span class=\"label\">Twitter</span></a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" class=\"icon circle fa-facebook\"><span class=\"label\">Facebook</span></a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" class=\"icon circle fa-google-plus\"><span class=\"label\">Google+</span></a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" class=\"icon circle fa-github\"><span class=\"label\">Github</span></a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" class=\"icon circle fa-dribbble\"><span class=\"label\">Dribbble</span></a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t\t<ul class=\"copyright\">\n");
      out.write("\t\t\t\t\t<li>&copy; Untitled</li><li>Design: <a href=\"http://html5up.net\">HTML5 UP</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t\t</footer>\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
